import type { Rule } from "./rules"

// JSON strings are valid YAML double-quoted scalars.
const q = (value: string): string => JSON.stringify(value)

/** A Prometheus rule file with one group. Deterministic, so drift is a byte comparison. */
export function renderRules(group: string, rules: readonly Rule[]): string {
  const lines = [
    "# Generated by `bun run metrics:rules`. Do not edit.",
    "groups:",
    `  - name: ${q(group)}`,
    "    rules:",
  ]

  for (const rule of rules) {
    lines.push(
      `      - alert: ${q(rule.alert)}`,
      `        expr: ${q(rule.expr)}`,
      `        for: ${q(rule.for)}`,
      "        labels:",
      `          severity: ${q(rule.severity)}`,
      "        annotations:",
      `          summary: ${q(rule.summary)}`,
    )
    if (rule.runbook !== undefined) lines.push(`          runbook_url: ${q(rule.runbook)}`)
  }

  return `${lines.join("\n")}\n`
}
